name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PIng-Pong-The-Game-in-C-.sln

      - name: Build
        run: dotnet build PIng-Pong-The-Game-in-C-.sln --no-restore --verbosity diag

      - name: Test
        run: dotnet test PIng-Pong-The-Game-in-C-.sln --no-build --verbosity normal
        continue-on-error: true  # Remove if you want workflow to stop on test failures
